spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  data:
    mongodb:
      uri: mongodb://192.168.2.2:27017/images
      database: images
  redis:
    host: 192.168.2.2
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydocker?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
  mail:
    host: smtp.163.com
    username: 15291418231@163.com
    password: KBYHHNIOBQVUSACC
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
          starttls:
            enable: true
            required: true
      test-connection: false
server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/*.xml