spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/images
      database: images
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
server:
  address: 127.0.0.1
  port: 8080