spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  data:
    mongodb:
      uri: mongodb://192.168.2.2:27017/images
      database: images
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydocker?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml