version : '3'
services:
  mydocker:
    container_name: mydocker-compose
    build:
      context: .
      dockerfile: Dockerfile-mydocker
    ports:
      - "8080:8080"
    volumes:
      - .:/vol/development
    depends_on:
      - mysql
      - mongodb
      - redis
    links:
      - "mysql:mysql"
      - "mongodb:mongodb"
      - "redis:redis"
    restart: always
    networks:
      - my-network
    environment:
      - TZ=Asia/Shanghai
  mongodb:
    image: daocloud.io/library/mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my-network
  mysql:
    container_name: mysql-compose
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_DATABASE: mydocker
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    restart: always
    networks:
      - my-network
networks:
  my-network: